# Generated by Django 3.2.7 on 2021-09-26 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentarios',
            old_name='publicado',
            new_name='publicado_comentario',
        ),
    ]
